// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh7X-c_lMFD9sQ3ISxE4OnVNSb2Qk-CEs',
    appId: '1:987296994681:web:1225ee0e68e99d39c50ba8',
    messagingSenderId: '987296994681',
    projectId: 'test-1-app-dist',
    authDomain: 'test-1-app-dist.firebaseapp.com',
    storageBucket: 'test-1-app-dist.firebasestorage.app',
    measurementId: 'G-L2GG2ZENQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFcJeqlZllSiESNpkmAdbrSWOs7G3-9SQ',
    appId: '1:987296994681:android:00332ca5991d382dc50ba8',
    messagingSenderId: '987296994681',
    projectId: 'test-1-app-dist',
    storageBucket: 'test-1-app-dist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgemAmwiih-Qmb2MmUfyAF8IAoDfcKWww',
    appId: '1:987296994681:ios:35198938f1085d79c50ba8',
    messagingSenderId: '987296994681',
    projectId: 'test-1-app-dist',
    storageBucket: 'test-1-app-dist.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgemAmwiih-Qmb2MmUfyAF8IAoDfcKWww',
    appId: '1:987296994681:ios:35198938f1085d79c50ba8',
    messagingSenderId: '987296994681',
    projectId: 'test-1-app-dist',
    storageBucket: 'test-1-app-dist.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh7X-c_lMFD9sQ3ISxE4OnVNSb2Qk-CEs',
    appId: '1:987296994681:web:3c15eb9e38dc46e0c50ba8',
    messagingSenderId: '987296994681',
    projectId: 'test-1-app-dist',
    authDomain: 'test-1-app-dist.firebaseapp.com',
    storageBucket: 'test-1-app-dist.firebasestorage.app',
    measurementId: 'G-102KN6WJT7',
  );

}